# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - Timer Trigger

on:
  push:
    branches:
      - master
    paths:
      # Targets your second trigger folder specifically
      - '02-function/02-trigger-function/**'
  workflow_dispatch:
  
env:
  # Targets your second trigger folder specifically
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '02-function/02-trigger-function' 
  DOTNET_VERSION: '10.0.x' 

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'some-weather-timer-function'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_TIMER_FUNCTION_PUBLISH_PROFILE }}
